app_version: 2.3.0
capabilities:
- description: Zigbee2MQTT is able to bind to a privileged port.
  name: NET_BIND_SERVICE
categories:
- home-automation
changelog_url: https://github.com/Koenkk/zigbee2mqtt/blob/master/CHANGELOG.md
date_added: '2024-12-24'
description: Zigbee to MQTT bridge get rid of your proprietary Zigbee bridges
home: https://www.zigbee2mqtt.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/zigbee2mqtt/icons/icon.svg
keywords:
- zigbee
- mqtt
- bridge
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: zigbee2mqtt
run_as_context:
- description: Zigbee2MQTT runs as any non-root user.
  gid: 568
  group_name: zigbee2mqtt
  uid: 568
  user_name: zigbee2mqtt
screenshots:
- https://media.sys.truenas.net/apps/zigbee2mqtt/screenshots/screenshot1.png
sources:
- https://github.com/Koenkk/zigbee2mqtt
title: Zigbee2MQTT
train: community
version: 1.0.27
