app_version: latest
capabilities: []
categories:
- productivity
changelog_url: https://docs.logseq.com/#/page/changelog
date_added: '2024-08-02'
description: Logseq is a privacy-first, open-source platform for knowledge management
  and collaboration.
home: https://logseq.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/logseq/icons/icon.png
keywords:
- knowledge
- management
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: logseq
run_as_context:
- description: Logseq runs as any non-root user.
  gid: 568
  group_name: logseq
  uid: 568
  user_name: logseq
screenshots: []
sources:
- https://github.com/logseq/logseq
title: Logseq
train: community
version: 1.1.12
