app_version: 1.0.0
capabilities: []
categories:
- custom
date_added: '2024-09-10'
description: An application for deploying simple containers.
home: https://www.truenas.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
keywords: []
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: ix-app
run_as_context: []
screenshots: []
sources: []
title: iX App
train: stable
version: 1.1.18
