app_version: 2025.5.15-cd64fb9
capabilities:
- description: SearXNG requires this ability to switch user for sub-processes.
  name: SETUID
- description: SearXNG requires this ability to switch group for sub-processes.
  name: SETGID
categories:
- productivity
changelog_url: https://github.com/searxng/searxng/commits/master/
date_added: '2024-09-13'
description: SearXNG is a privacy-respecting, hackable metasearch engine
home: https://github.com/searxng/searxng
host_mounts: []
icon: https://media.sys.truenas.net/apps/searxng/icons/icon.svg
keywords:
- search
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: searxng
run_as_context:
- description: SearXNG runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
- description: Redis runs as a non-root user and root group.
  gid: 0
  group_name: root
  uid: 1001
  user_name: redis
screenshots: []
sources:
- https://hub.docker.com/r/searxng/searxng
- https://github.com/searxng/searxng
title: SearXNG
train: community
version: 1.1.82
