app_version: 1.26.2
capabilities:
- description: FreshRSS is able to chown files.
  name: CHOWN
- description: FreshRSS is able to set group ID for it's sub-processes.
  name: SETGID
- description: FreshRSS is able to set user ID for it's sub-processes.
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/FreshRSS/FreshRSS/blob/edge/CHANGELOG.md
date_added: '2024-08-09'
description: FreshRSS is a free, self-hostable news aggregator
home: https://freshrss.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/freshrss/icons/icon.png
keywords:
- rss
- news
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: freshrss
run_as_context:
- description: FreshRSS runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
screenshots:
- https://media.sys.truenas.net/apps/freshrss/screenshots/screenshot1.webp
sources:
- https://github.com/FreshRSS/FreshRSS
- https://hub.docker.com/r/freshrss/freshrss
title: FreshRSS
train: community
version: 1.3.20
