app_version: 4.0.9
capabilities: []
categories:
- productivity
changelog_url: https://github.com/node-red/node-red-docker/releases
date_added: '2024-08-02'
description: Node-RED is a programming tool for wiring together hardware devices,
  APIs and online services in new and interesting ways.
home: https://nodered.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/node-red/icons/icon.png
keywords:
- automation
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: node-red
run_as_context:
- description: Node-RED runs as a non-root user.
  gid: 1000
  group_name: node-red
  uid: 1000
  user_name: node-red
screenshots:
- https://media.sys.truenas.net/apps/node-red/screenshots/screenshot1.png
sources:
- https://nodered.org
- https://github.com/node-red/node-red-docker
title: Node-RED
train: community
version: 1.1.15
