app_version: 2.7.11
capabilities: []
categories:
- database
changelog_url: https://docs.influxdata.com/influxdb/v2/reference/release-notes/influxdb/
date_added: '2025-01-31'
description: Scalable datastore for metrics, events, and real-time analytics
home: https://influxdata.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/influxdb/icons/icon.png
keywords:
- metrics
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: influxdb
run_as_context:
- description: InfluxDB runs as any non-root user.
  gid: 568
  group_name: influxdb
  uid: 568
  user_name: influxdb
screenshots: []
sources:
- https://github.com/influxdata/influxdb
- https://github.com/influxdata/influxdata-docker
title: InfluxDB
train: community
version: 1.0.6
