app_version: stable
capabilities: []
categories:
- media
date_added: '2025-05-06'
description: NextPVR is a personal video recorder application, with the goal making
  it easy to watch or record live TV
home: http://nextpvr.com/
host_mounts:
- description: Digital Video Broadcast (DVB) device
  host_path: /dev/dvb
icon: https://media.sys.truenas.net/apps/nextpvr/icons/icon.webp
keywords:
- nextpvr
- livetv
- streaming
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: nextpvr
run_as_context:
- description: NextPVR runs as non-root user.
  gid: 568
  group_name: nextpvr
  uid: 568
  user_name: nextpvr
screenshots: []
sources:
- https://hub.docker.com/r/nextpvr/nextpvr_amd64
title: NextPVR
train: community
version: 1.0.2
