app_version: 9.9.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/sassanix/Warracker/blob/main/CHANGELOG.md
date_added: '2025-04-10'
description: Warracker is an open-source web application to manage product warranties,
  track expiration dates, and store related documents.
home: https://github.com/sassanix/Warracker
host_mounts: []
icon: https://media.sys.truenas.net/apps/warracker/icons/icon.png
keywords:
- warranty
- expiration
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: warracker
run_as_context:
- description: Warracker runs as any non-root user.
  gid: 568
  group_name: warracker
  uid: 568
  user_name: warracker
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
screenshots:
- https://media.sys.truenas.net/apps/warracker/screenshots/screenshot1.png
sources:
- https://github.com/sassanix/Warracker
title: Warracker
train: community
version: 1.0.8
