app_version: v2.15.2
capabilities: []
categories:
- media
changelog_url: https://github.com/Tautulli/Tautulli/blob/master/CHANGELOG.md
date_added: '2024-08-02'
description: Tautulli is a python based web application for monitoring, analytics
  and notifications for Plex Media Server.
home: https://tautulli.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/tautulli/icons/icon.png
keywords:
- media
- analytics
- notifications
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: tautulli
run_as_context:
- description: Tautulli runs as any non-root user.
  gid: 568
  group_name: tautulli
  uid: 568
  user_name: tautulli
screenshots:
- https://media.sys.truenas.net/apps/tautulli/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/tautulli/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/tautulli/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/tautulli/screenshots/screenshot4.png
sources:
- https://github.com/Tautulli/Tautulli
title: Tautulli
train: community
version: 1.1.16
