app_version: 5.5.2
capabilities: []
categories:
- security
changelog_url: https://github.com/Bubka/2FAuth/blob/master/changelog.md
date_added: '2024-09-18'
description: 2FAuth is a web based self-hosted alternative to One Time Passcode (OTP)
  generators like Google Authenticator, designed for both mobile and desktop.
home: https://docs.2fauth.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/twofactor-auth/icons/icon.png
keywords:
- security
- 2fa
- otp
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: twofactor-auth
run_as_context:
- description: 2FAuth runs as non-root user.
  gid: 1000
  group_name: 2fauth
  uid: 1000
  user_name: 2fauth
screenshots:
- https://media.sys.truenas.net/apps/twofactor-auth/screenshots/screenshot1.png
sources:
- https://github.com/Bubka/2FAuth
- https://hub.docker.com/r/2fauth/2fauth/
title: 2FAuth
train: community
version: 1.1.16
