app_version: 2.1.0.5
capabilities: []
categories:
- backup
changelog_url: https://github.com/duplicati/duplicati/releases
date_added: '2025-02-12'
description: Store securely encrypted backups in the cloud!
home: http://duplicati.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/duplicati/icons/icon.png
keywords:
- backup
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: duplicati
run_as_context:
- description: Duplicati runs as any non-root user.
  gid: 568
  group_name: duplicati
  uid: 568
  user_name: duplicati
screenshots: []
sources:
- https://github.com/duplicati/duplicati
- https://hub.docker.com/r/duplicati/duplicati
title: Duplicati
train: community
version: 1.0.10
