app_version: v3.3.1
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/prometheus/prometheus/releases/
date_added: '2024-08-02'
description: The Prometheus monitoring system and time series database.
home: https://prometheus.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/prometheus/icons/icon.png
keywords:
- metrics
- prometheus
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: prometheus
run_as_context:
- description: Prometheus runs as any non-root user.
  gid: 568
  group_name: prometheus
  uid: 568
  user_name: prometheus
screenshots:
- https://media.sys.truenas.net/apps/prometheus/screenshots/screenshot1.png
sources:
- https://github.com/prometheus/prometheus
- https://prometheus.io
title: Prometheus
train: stable
version: 1.2.21
