app_version: 2.5.3
capabilities: []
categories:
- financial
changelog_url: https://github.com/Chia-Network/chia-blockchain/releases
date_added: '2024-08-21'
description: Chia is a modern cryptocurrency built from scratch, designed to be efficient,
  decentralized, and secure.
home: https://www.chia.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/chia/icons/icon.svg
keywords:
- blockchain
- hard-drive
- chia
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: chia
run_as_context:
- description: Chia runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots: []
sources:
- https://github.com/Chia-Network/chia-docker
- https://www.chia.net/
title: Chia
train: community
version: 1.1.15
