app_version: 2.0.21
capabilities: []
categories:
- networking
changelog_url: https://github.com/eclipse-mosquitto/mosquitto/blob/master/ChangeLog.txt
date_added: '2024-11-15'
description: Eclipse Mosquitto is an open source MQTT broker
home: https://mosquitto.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/eclipse-mosquitto/icons/icon.svg
keywords:
- networking
- mqtt
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: eclipse-mosquitto
run_as_context:
- description: Mosquitto runs as any non-root user.
  gid: 568
  group_name: mosquitto
  uid: 568
  user_name: mosquitto
screenshots: []
sources:
- https://github.com/eclipse-mosquitto/mosquitto
- https://hub.docker.com/_/eclipse-mosquitto
title: Eclipse Mosquitto
train: community
version: 1.0.15
