app_version: RELEASE.2025-04-22T22-12-26Z
capabilities: []
categories:
- storage
date_added: '2024-07-31'
description: High Performance, Kubernetes Native Object Storage
home: https://min.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
keywords:
- object storage
- minio
- cloud
- s3
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: minio
run_as_context:
- description: MinIO runs as any non-root user.
  gid: 568
  group_name: minio
  uid: 568
  user_name: minio
screenshots:
- https://media.sys.truenas.net/apps/adguard-home/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/adguard-home/screenshots/screenshot2.png
sources:
- https://github.com/minio/minio
title: MinIO
train: enterprise
version: 1.2.23
