app_version: v0.13.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/C4illin/ConvertX/releases
date_added: '2025-05-05'
description: ConvertX is a self-hosted online file converter with support for over
  1000 formats
home: https://github.com/C4illin/ConvertX
host_mounts: []
icon: https://media.sys.truenas.net/apps/convertx/icons/icon.png
keywords:
- convertx
- files
- conversion
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: convertx
run_as_context:
- description: ConvertX runs as any non-root user.
  gid: 568
  group_name: convertx
  uid: 568
  user_name: convertx
screenshots: []
sources:
- https://github.com/C4illin/ConvertX
title: ConvertX
train: community
version: 1.0.2
