app_version: 1.39.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/sissbruecker/linkding/releases
date_added: '2024-09-03'
description: Linkding is a bookmark manager that you can host yourself.
home: https://github.com/sissbruecker/linkding
host_mounts: []
icon: https://media.sys.truenas.net/apps/linkding/icons/icon.svg
keywords:
- bookmark
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: linkding
run_as_context:
- description: Linkding runs as any non-root user.
  gid: 568
  group_name: linkding
  uid: 568
  user_name: linkding
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
screenshots:
- https://media.sys.truenas.net/apps/linkding/screenshots/screenshot1.png
sources:
- https://github.com/sissbruecker/linkding
- https://hub.docker.com/r/sissbruecker/linkding/
title: Linkding
train: community
version: 1.2.18
