app_version: 1.36.1.5049
capabilities: []
categories:
- media
changelog_url: https://github.com/Prowlarr/Prowlarr/releases
date_added: '2024-07-31'
description: Prowlarr is an indexer manager/proxy to integrate with your various PVR
  apps.
home: https://prowlarr.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/prowlarr/icons/icon.png
keywords:
- indexer
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: prowlarr
run_as_context:
- description: Prowlarr runs as any non-root user.
  gid: 568
  group_name: prowlarr
  uid: 568
  user_name: prowlarr
screenshots:
- https://media.sys.truenas.net/apps/prowlarr/screenshots/screenshot1.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/prowlarr
- https://prowlarr.com
title: Prowlarr
train: community
version: 1.3.37
