app_version: 4.100.1
capabilities:
- description: Code Server is able to chown files.
  name: CHOWN
- description: Code Server is able to bypass permission checks.
  name: DAC_OVERRIDE
categories:
- development
changelog_url: https://github.com/coder/code-server/blob/main/CHANGELOG.md
date_added: '2025-04-03'
description: Code Server is VS Code in the browser
home: https://coder.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/code-server/icons/icon.png
keywords:
- code
- editor
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: code-server
run_as_context:
- description: Code Server runs as any non-root user.
  gid: 568
  group_name: code-server
  uid: 568
  user_name: code-server
screenshots: []
sources:
- https://github.com/coder/code-server
title: Code Server
train: community
version: 1.0.10
