app_version: 12.0.0
capabilities: []
categories:
- productivity
changelog_url: https://grafana.com/docs/grafana/latest/whatsnew/
date_added: '2024-08-01'
description: Grafana is the open source analytics & monitoring solution for every
  database.
home: https://grafana.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/grafana/icons/icon.png
keywords:
- analytics
- monitoring
- metrics
- dashboards
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: grafana
run_as_context:
- description: Grafana runs as any non-root user.
  gid: 568
  group_name: grafana runs as any non-root user.
  uid: 568
  user_name: grafana runs as any non-root user.
screenshots:
- https://media.sys.truenas.net/apps/grafana/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/grafana/screenshots/screenshot2.png
sources:
- https://hub.docker.com/r/grafana/grafana
- https://github.com/grafana
title: Grafana
train: community
version: 1.2.20
