app_version: 4.9.3
capabilities: []
categories:
- media
changelog_url: https://github.com/jesec/flood/releases
date_added: '2025-03-10'
description: A modern web UI for various torrent clients with a Node.js backend and
  React frontend.
home: https://flood.js.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/flood/icons/icon.png
keywords:
- torrent
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: flood
run_as_context:
- description: Flood runs as non-root user.
  gid: 1000
  group_name: flood
  uid: 1000
  user_name: flood
screenshots:
- https://media.sys.truenas.net/apps/flood/screenshots/screenshot1.png
sources:
- https://github.com/jesec/flood
- https://hub.docker.com/r/jesec/flood
title: Flood
train: community
version: 1.0.3
