app_version: 2.6.3
capabilities:
- description: Heimdall is able to chown files.
  name: CHOWN
- description: Heimdall is able to bypass permission checks.
  name: DAC_OVERRIDE
- description: Heimdall is able bypass permission checks for it's sub-processes.
  name: FOWNER
- description: Heimdall is able to set group ID for it's sub-processes.
  name: SETGID
- description: Heimdall is able to set user ID for it's sub-processes.
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/linuxserver/Heimdall/releases/
date_added: '2025-02-05'
description: An Application dashboard and launcher
home: https://heimdall.site/
host_mounts: []
icon: https://media.sys.truenas.net/apps/heimdall/icons/icon.png
keywords:
- dashboard
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: heimdall
run_as_context:
- description: Heimdall runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots: []
sources:
- https://github.com/linuxserver/Heimdall
- https://github.com/linuxserver/docker-heimdall
title: Heimdall
train: community
version: 1.0.6
