app_version: 4.0.6
capabilities: []
categories:
- media
changelog_url: https://github.com/transmission/transmission/releases/
date_added: '2024-09-19'
description: Transmission is designed for easy, powerful use.
home: https://transmissionbt.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/transmission/icons/icon.png
keywords:
- media
- torrent
- download
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: transmission
run_as_context:
- description: Transmission runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots: []
sources:
- https://docs.linuxserver.io/images/docker-transmission/#parameters
- https://transmissionbt.com/
- https://github.com/linuxserver/docker-transmission
title: Transmission
train: community
version: 1.1.17
