app_version: v3.3.21
capabilities: []
categories:
- networking
changelog_url: https://github.com/FlareSolverr/FlareSolverr/blob/master/CHANGELOG.md
date_added: '2024-10-24'
description: FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.
home: https://github.com/FlareSolverr/FlareSolverr
host_mounts: []
icon: https://media.sys.truenas.net/apps/flaresolverr/icons/icon.svg
keywords:
- networking
- captcha
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: flaresolverr
run_as_context:
- description: FlareSolverr runs as non-root user.
  gid: 1000
  group_name: flaresolverr
  uid: 1000
  user_name: flaresolverr
screenshots: []
sources:
- https://github.com/FlareSolverr/FlareSolverr
title: FlareSolverr
train: community
version: 1.0.21
