app_version: v2.9.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/qdm12/ddns-updater/releases
date_added: '2024-08-01'
description: Lightweight universal DDNS Updater with web UI
home: https://github.com/qdm12/ddns-updater
host_mounts: []
icon: https://media.sys.truenas.net/apps/ddns-updater/icons/icon.svg
keywords:
- ddns-updater
- ddns
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: ddns-updater
run_as_context:
- description: DDNS Updater runs as any non-root user.
  gid: 568
  group_name: ddns-updater
  uid: 568
  user_name: ddns-updater
screenshots:
- https://media.sys.truenas.net/apps/ddns-updater/screenshots/screenshot1.png
sources:
- https://github.com/qdm12/ddns-updater
- https://hub.docker.com/r/qmcgaw/ddns-updater
title: DDNS Updater
train: community
version: 1.1.18
