app_version: 1.5.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/Spottarr/Spottarr/releases
date_added: '2025-04-24'
description: Spottarr is a small application that can index the spotnet messages (spots)
  and exposes them as a newznab indexer.
home: https://github.com/Spottarr/Spottarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/spottarr/icons/icon.svg
keywords:
- media
- newsserver
- download
- newznab
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: spottarr
run_as_context:
- description: Spottarr runs as any non-root user.
  gid: 568
  group_name: spottarr
  uid: 568
  user_name: spottarr
sources:
- https://github.com/Spottarr/Spottarr
title: Spottarr
train: community
version: 1.0.9
