app_version: '29.0'
capabilities: []
categories:
- financial
date_added: '2025-04-22'
description: Run your personal node powered by Bitcoin Core.
home: https://bitcoin.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitcoind/icons/icon.png
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.1.27
lib_version_hash: 565d2e69b987753ffbe487136ed3c370444e4e3d656729c22823d535141526cf
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: bitcoind
run_as_context:
- description: Bitcoin Node runs as non-root user.
  gid: 1000
  group_name: bitcoin
  uid: 1000
  user_name: bitcoin
screenshots: []
sources:
- https://bitcoin.org
- https://github.com/sethforprivacy/docker-bitcoind
title: Bitcoin Node
train: community
version: 1.0.3
