app_version: e65abd21-ls144
capabilities:
- description: LazyLibrarian is able to chown files.
  name: CHOWN
- description: LazyLibrarian is able to bypass permission checks.
  name: DAC_OVERRIDE
- description: LazyLibrarian is able bypass permission checks for it's sub-processes.
  name: FOWNER
- description: LazyLibrarian is able to set group ID for it's sub-processes.
  name: SETGID
- description: LazyLibrarian is able to set user ID for it's sub-processes.
  name: SETUID
categories:
- media
changelog_url: https://github.com/linuxserver/docker-lazylibrarian/releases
date_added: '2025-04-22'
description: LazyLibrarian is a program to follow authors and grab metadata for all
  your digital reading needs.
home: https://gitlab.com/LazyLibrarian/LazyLibrarian
host_mounts: []
icon: https://media.sys.truenas.net/apps/lazylibrarian/icons/icon.webp
keywords:
- media
- ebooks
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: lazylibrarian
run_as_context:
- description: LazyLibrarian runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
sources:
- https://github.com/linuxserver/docker-lazylibrarian
- https://gitlab.com/LazyLibrarian/LazyLibrarian
title: LazyLibrarian
train: community
version: 1.0.2
