app_version: 5.1.0
capabilities: []
categories:
- media
changelog_url: https://www.qbittorrent.org/news
date_added: '2024-07-30'
description: The qBittorrent project aims to provide an open-source software alternative
  to mTorrent.
home: https://www.qbittorrent.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/qbittorrent/icons/icon.png
keywords:
- media
- torrent
- download
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: qbittorrent
run_as_context:
- description: qBittorrent runs as any non-root user.
  gid: 568
  group_name: qbittorrent
  uid: 568
  user_name: qbittorrent
screenshots:
- https://media.sys.truenas.net/apps/qbittorrent/screenshots/screenshot1.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/qbittorrent
- https://www.qbittorrent.org/
title: qBittorrent
train: community
version: 1.1.23
