app_version: 0.9
capabilities: []
categories:
- productivity
changelog_url: https://github.com/brufdev/many-notes/releases
date_added: '2025-06-13'
description: Many Notes is a Markdown note-taking web application
  designed for simplicity! Easily create or import your vaults and
  organize your thoughts right away.
home: https://github.com/brufdev/many-notes
host_mounts: []
icon: https://media.sys.truenas.net/apps/many-notes/icons/icon.png
keywords:
- documentation
- knowledgebase
lib_version: 2.1.35
lib_version_hash: 1bd4e0058fbd4d7c207df2cae606580065e8e6dba3e232f41bc1b006848b05d2
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: many-notes
run_as_context:
- description: Many Notes runs as any non-root user.
  gid: 568
  group_name: manynotes
  uid: 568
  user_name: manynotes
screenshots: []
sources:
- https://github.com/brufdev/many-notes
title: Many Notes
train: community
version: 1.0.0
