app_version: v8.12.15
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/amir20/dozzle/releases
date_added: '2025-01-31'
description: Realtime log viewer for docker containers.
home: https://dozzle.dev
host_mounts: []
icon: https://media.sys.truenas.net/apps/dozzle/icons/icon.svg
keywords:
- logs
lib_version: 2.1.27
lib_version_hash: 10c53adc181dff684987a8a3716cdaf9e3d56934bde39ce1ef3c57241b6043b1
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: dozzle
run_as_context:
- description: Dozzle runs as any non-root user.
  gid: 568
  group_name: dozzle
  uid: 568
  user_name: dozzle
screenshots: []
sources:
- https://github.com/amir20/dozzle
title: Dozzle
train: community
version: 1.0.29
